### ISSUE TITLE
Getting error intermittently "Object reference not set to an instance of an object."

### ISSUE THREAD

**Issue by rudolphk-om** [nreco/csv#9]
Stack trace:
at NReco.Csv.CsvReader.GetOrAddField(Int32 startIdx)
   at NReco.Csv.CsvReader.Read()

Using version 1.0.1

**Comment by rudolphk-om** [comment]
I can give you a file, but it happens in different lines every time. I am quickly checking if I include the source in my project, if it will give me a better understanding of what is going wrong.

**Comment by VitaliyMF** [comment]
I don't need the source of your project -- only steps how to reproduce the issue. Ideally if you can a small [unit test here](https://github.com/nreco/csv/tree/master/src/NReco.Csv.Tests) that fails.

**Comment by rudolphk-om** [comment]
No, what I meant was instead of referencing the project by Nuget. I include this project's source code, so I can debug the issue. I am not currently getting consistent scenario where this happens as its very intermittent.

**Comment by rudolphk-om** [comment]
Very weird as I am not getting the same error when I include the project as part of my source code vs referencing it via Nuget. I've checked and it looks like the Nuget is exactly the same as the one in Github, date wise.

**Comment by VitaliyMF** [comment]
It's hard to believe that code behavior may depend on nuget reference vs code compiled as part of your project.

Most likely, there should be certain conditions (very specific CSV input, for instance). In fact this CSV parser's code is used in BI tool (for many years - since 2017) where end-users upload their CSV files, so this parser tested against thousands and thousands of real-life CSV files.

**Comment by rudolphk-om** [comment]
Yes, I don't understand this either. You can resolve the issue for now.
